%% User Journey 2 - Roger Valenzuela (Jefe de Activos) - Activa360
journey
  title Journey Roger Valenzuela – Localizar activo específico

  section Consulta
    Ingresa código o nombre de activo: 5: Roger
    Sistema muestra ubicación actual: 5: Roger
    Consulta historial de movimientos: 4: Roger

  section Acción
    Solicita verificación a custodio: 3: Roger
    Recibe confirmación: 4: Roger
    Actualiza registro si es necesario: 5: Roger
